### ISSUE TITLE
Can't build on Ubuntu 18.04.5

### ISSUE THREAD

**Issue by derritter88** [tulir/mautrix-whatsapp#220]
Hi there,

as Ubuntu 18.04 does only feature libolm2 I wanted to build the bridge according your wiki
_If you use libolm2 (currently in Debian stable), use ./build.sh -tags nosas to build in libolm2 compatibility mode._ 

Unfortunately I get multiple compiler errors:

/root/go/pkg/mod/maunium.net/go/mautrix@v0.7.2/crypto/keysharing.go:152:13: mach.sendToOneDevice undefined (type *OlmMachine has no field or method sendToOneDevice)
/root/go/pkg/mod/maunium.net/go/mautrix@v0.7.2/crypto/keysharing.go:156:12: mach.sendToOneDevice undefined (type *OlmMachine has no field or method sendToOneDevice)
/root/go/pkg/mod/maunium.net/go/mautrix@v0.7.2/crypto/machine.go:46:56: undefined: VerificationRequestResponse
/root/go/pkg/mod/maunium.net/go/mautrix@v0.7.2/crypto/machine.go:46:85: undefined: VerificationHooks
/root/go/pkg/mod/maunium.net/go/mautrix@v0.7.2/crypto/machine.go:76:58: undefined: VerificationRequestResponse
/root/go/pkg/mod/maunium.net/go/mautrix@v0.7.2/crypto/machine.go:76:87: undefined: VerificationHooks
/root/go/pkg/mod/maunium.net/go/mautrix@v0.7.2/crypto/verification_sas_methods.go:29:30: undefined: olm.SAS
/root/go/pkg/mod/maunium.net/go/mautrix@v0.7.2/crypto/verification_sas_methods.go:50:29: undefined: olm.SAS
/root/go/pkg/mod/maunium.net/go/mautrix@v0.7.2/crypto/verification_sas_methods.go:171:29: undefined: olm.SAS
/root/go/pkg/mod/maunium.net/go/mautrix@v0.7.2/crypto/machine.go:76:58: too many errors

**Comment by derritter88** [comment]
Upgraded to 20.04 - no more issues
